### ISSUE TITLE
do your codes trained on cpu or gpu?

### ISSUE THREAD

**Issue by longmalongma** [iMoonLab/HGNN#10]
do your codes trained on cpu or gpu?it only 18s?why it so quick?
Epoch 550/599
train Loss: 0.0548 Acc: 0.9879
val Loss: 0.6185 Acc: 0.9603
Best val Acc: 0.968801
--------------------

Training complete in 0m 18s
Best val Acc: 0.968801

**Comment by yifanfeng97** [comment]
It's normal speed for a graph-based convolution model. Simply speaking, It only computes serval fc layers. Each epoch only executes one batch.
