### ISSUE TITLE
features

### ISSUE THREAD

**Issue by 16619884724** [iMoonLab/HGNN#12]
Hello, your work is excellent, and I am very interested in it. Do the extracted GVCNN features you used refer to the final shape descriptor that has performed  grouping and inter-group fusion? I know that GVCNN is also your work, but there is no relevant open source code. Would you please provide some code? Thank you

**Comment by yifanfeng97** [comment]
Thank you for your attention. 
For the used feature: we use the feature map that just before the first fully connected layer.
For source code: Unfortunately, I'm so busy recently (especially the two weeks). Fortunately, I plan to release the verified GVCNN source code soon.

**Comment by 16619884724** [comment]
OK,It is so kind of you.Looking forward to your source code and next work.Thanks again for your reply


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yifan Feng(丰一帆)"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午2:34
收件人:&nbsp;"iMoonLab/HGNN"<HGNN@noreply.github.com&gt;;
抄送:&nbsp;"Confession"<1773507074@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iMoonLab/HGNN] features (#12)




Thank you for your attention.
 For the used feature: we use the feature map that just before the first fully connected layer.
 For source code: Unfortunately, I'm so busy recently (especially the two weeks). Fortunately, I plan to release the verified GVCNN source code soon.

**Comment by yifanfeng97** [comment]
Done! I'll close it.
