### ISSUE TITLE
Baseline enquiry

### ISSUE THREAD

**Issue by amblee0306** [iMoonLab/HGNN#15]
Hi there,

I would like to know how did you get the performance on GCN for the ModelNet40 and if you can make the code available? Another thing is that how can I generate the Adjacency matrix for ModelNet40 using the function `load_feature_construct_H`? is it just by setting K_neigs=[10] to [1]?

Thanks!

**Comment by echoisr** [comment]
again, I have the same problem

**Comment by yifanfeng97** [comment]
GCN's performance is achieved by directly adding the adjacency matrix constructed from MVCNN features and GVCNN features.
