### ISSUE TITLE
Issue about code with citation dataset

### ISSUE THREAD

**Issue by icmpnorequest** [iMoonLab/HGNN#16]
Hi Yifan,

Could you please upload the code with citation dataset? I was wondering how to transform dataset like raw cora (`cora.content` and `cora.cites`) to fit for hypergraph neural network. Thanks in advance.

**Comment by echoisr** [comment]
I have the same problem

**Comment by readergy** [comment]
Hi, were you able to solve this issue?Please give me some advice, thank you.

**Comment by readergy** [comment]
> I have the same problem

Hi, were you able to solve this issue?Please give me some advice, thank you.

**Comment by readergy** [comment]
> Hi Yifan,
> 
> Could you please upload the code with citation dataset? I was wondering how to transform dataset like raw cora (`cora.content` and `cora.cites`) to fit for hypergraph neural network. Thanks in advance.

Hi, were you able to solve this issue?Please give me some advice, thank you.

**Comment by upup179** [comment]
I am also interested in how to transform cora dataset to fit for hypergraph neural network,Would you give me some advice，thank you.

**Comment by liang-ry** [comment]
> > Hi Yifan,
> > Could you please upload the code with citation dataset? I was wondering how to transform dataset like raw cora (`cora.content` and `cora.cites`) to fit for hypergraph neural network. Thanks in advance.
> 
> Hi, were you able to solve this issue?Please give me some advice, thank you.

Hi，Have you solved the problem yet? Please give me some advice, thank you.

**Comment by yifanfeng97** [comment]
Hi
We have released a toolbox named  [DHG](https://github.com/iMoonLab/DeepHypergraph), which provides learning on many correlation structures like simple graph, bipartite graph, and simple hypergraph.
The structure transforms like promoting simple graph to hypergraph and reducing hypergraph to graph are also included in [here](https://deephypergraph.readthedocs.io/en/latest/tutorial/structure.html).
Use HGNN to learn on Cora refer to [this](https://deephypergraph.readthedocs.io/en/latest/examples/vertex_cls/graph.html#hgnn-on-cora)
Use HGNN+ to learn on Cora refer to [this](https://deephypergraph.readthedocs.io/en/latest/examples/vertex_cls/graph.html#)
Transform cora data to hypergraph data refer to [this](https://deephypergraph.readthedocs.io/en/latest/tutorial/structure.html#prometed-from-low-order-structures)
Hope this can help you!
