### ISSUE TITLE
What's the difference between the adjacency matrix and the incidence matrix on cora and Pubmed dataset？

### ISSUE THREAD

**Issue by bbjy** [iMoonLab/HGNN#5]
Hi, thank you for your work! But , I have a question as I  stated in the issue's title. "What's the difference between the adjacency matrix and the incidence matrix on cora and Pubmed dataset？"
I think that they are the same. Right?
Looking forward to your reply, Thank you!

**Comment by yifanfeng97** [comment]
Hi, thank you for your attention. Here, we construct hyperedge from their one-hop neighbors for each node. If you don't concatenate extra hyperedge to existing citation constructed incidence matrix, they are just the same in the number but thorough different in mathematical. We can also construct hyperedge from the combination of one-hop and two-hop neighbors for each node. Hypergraph incidence matrix is more flexible than the graph adjacency matrix.

**Comment by bbjy** [comment]
I understand, thank you!
