### ISSUE TITLE
Question about feature file

### ISSUE THREAD

**Issue by ZhenpengChenCode** [iMoonLab/HGNN#6]
Hi, the project performed very well. Thank you for your contribution.
I have a question about the data. How to create the feature file?
Can you shared the code?

**Comment by yifanfeng97** [comment]
Hi, thank you for your attention! Well, as we said in our paper the MVCNN (Su et al. ICCV 2015)/GVCNN (Feng et al. CVPR 2018) is employed here to extract visual feature from the 3D object in ModelNet40.  Specifically, we both select the output of the layer just before the last fully connected layer in the classifier, which owns 4096 dimensions for MVCNN (VGG-based) and 2048 dimensions for GVCNN (GoogLeNet-based). After getting features, we organize them in the file with the letter spelling of each object name, respectively. 

For more implement detail of the feature extracting framework, you can refer to [Multi-view Convolutional Neural Networks for 3D Shape Recognition] and [GVCNN: Group-View Convolutional Neural Networks for 3D Shape Recognition].
