### ISSUE TITLE
ANN integration with hypergraph construction

### ISSUE THREAD

**Issue by jlevy44** [iMoonLab/HGNN#7]
Hi there! For large high dimensional datasets, could some ANN library like HNSW be integrated into construct_H_with_KNN ? Maybe called construct_H_with_ANN?

Thanks!

**Comment by yifanfeng97** [comment]
Good suggestion. Thanks!

**Comment by yifanfeng97** [comment]
We will release a deep-hypergraph operation library soon. The ANN operator will be included.

**Comment by jlevy44** [comment]
Awesome. Looking forward to it!

**Comment by yifanfeng97** [comment]
Our hypergraph deep learning library is available on https://github.com/iMoonLab/THU-torch_hyperg.

**Comment by jlevy44** [comment]
Thank you! Wonderful work!
