### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by longmalongma** [iMoonLab/HGNN#9]
----------
Epoch 500/599
train Loss: 0.0554 Acc: 0.9868
val Loss: 0.5913 Acc: 0.9611
Best val Acc: 0.968801
--------------------
----------
Epoch 550/599
train Loss: 0.0548 Acc: 0.9879
val Loss: 0.6185 Acc: 0.9603
Best val Acc: 0.968801
--------------------

Training complete in 0m 18s
Best val Acc: 0.968801
how to test on ModelNet40 dataset?

**Comment by yifanfeng97** [comment]
ModelNet40 only have train/val set.
